pull_request_rules:
  - name: Automatic merge for passing scala-steward PRs
    conditions:
      - or:
        - author=chadford
        - head~=^update/.?$
      - base=master
    actions:
      merge:
        method: rebase
