//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.3")
addSbtPlugin("io.spray"      % "sbt-revolver"       % "0.9.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"       % "0.9.18")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"       % "2.4.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage"      % "1.6.1")
addSbtPlugin("org.duhemm"    % "sbt-errors-summary" % "0.6.3")
