//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.3")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"  % "0.14.3")
addSbtPlugin("io.spray"      % "sbt-revolver"  % "0.10.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"  % "2.5.4")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.3.1")
