//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.3")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"       % "0.9.15")
addSbtPlugin("io.spray"      % "sbt-revolver"       % "0.9.1")
addSbtPlugin("org.duhemm"    % "sbt-errors-summary" % "0.6.3")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"       % "2.3.4")
addSbtPlugin("org.scoverage" % "sbt-scoverage"      % "1.6.1")
