name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2

    - name: Cache ivy2 files
      uses: actions/cache@v1
      env:
        cache-name: cache-ivy2-files
      with:
        path: ~/.ivy2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'
    - name: Run tests
      run: sbt coverageOn test coverageReport
